# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FeederApp', '0005_auto_20161102_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_branch', models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CL', 'Chemical Engineering')], max_length=2)),
                ('course_credits', models.IntegerField()),
                ('course_semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ASS', 'Assignment'), ('EX', 'Examination'), ('FD', 'FeedBack')], max_length=3)),
                ('desc', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=10)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FeederApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeederApp.Course')),
                ('deadline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FeederApp.Deadlines')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_branch', models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CL', 'Chemical Engineering')], max_length=2, null=True)),
                ('instructor_dob', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('RB', 'Radio Buttons'), ('TF', 'Text Field')], max_length=2)),
                ('response', models.TextField(null=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FeederApp.Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10, null=True)),
                ('student_branch', models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CL', 'Chemical Engineering')], max_length=2, null=True)),
                ('student_dob', models.DateField(null=True)),
                ('student_program', models.CharField(choices=[('BT', 'B.Tech.'), ('MT', 'M.Tech.'), ('DD', 'Dual Degree')], max_length=2, null=True)),
                ('student_year', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='FeederApp.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='FeederApp.Student'),
        ),
    ]
