# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=100)),
                ('student_ldap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_branch', models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CH', 'Chemical Engineering')], max_length=2)),
                ('student_year', models.IntegerField()),
                ('student_dob', models.DateField()),
            ],
        ),
    ]
