# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FeederApp', '0004_auto_20161019_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ldap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_branch', models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CH', 'Chemical Engineering')], max_length=2)),
                ('student_year', models.IntegerField()),
                ('student_dob', models.DateField()),
                ('student_program', models.CharField(choices=[('BT', 'B.Tech.'), ('MT', 'M.Tech.'), ('DD', 'Dual Degree')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
