# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0006_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_branch',
            field=models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CL', 'Chemical Engineering')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CL', 'Chemical Engineering')], max_length=2),
        ),
    ]
