# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0008_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
