# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0009_auto_20161019_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_branch', models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CL', 'Chemical Engineering')], max_length=2)),
                ('course_credits', models.IntegerField()),
                ('course_duration', models.DecimalField(decimal_places=1, max_digits=2)),
                ('instructors', models.ManyToManyField(to='FeederApp.Instructor')),
                ('students', models.ManyToManyField(to='FeederApp.Student')),
            ],
        ),
    ]
