# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0013_auto_20161029_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
