# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0023_auto_20161029_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FeederApp.Question'),
        ),
    ]
