# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0007_remove_instructor_instructor_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('RB', 'Radio Buttons'), ('TF', 'Text Field'), ('MCQ', 'Multiple Choice Question'), ('CB', 'Check Boxes'), ('DD', 'Drop Down List')], max_length=2),
        ),
    ]
