# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0008_auto_20161103_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='stud',
            field=models.ManyToManyField(to='FeederApp.Student'),
        ),
    ]
