# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_branch',
            field=models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CL', 'Chemical Engineering')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CL', 'Chemical Engineering')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_program',
            field=models.CharField(choices=[('BT', 'B.Tech.'), ('MT', 'M.Tech.'), ('DD', 'Dual Degree')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_year',
            field=models.IntegerField(null=True),
        ),
    ]
