# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeederApp', '0004_auto_20161031_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='studentsresponded',
            field=models.TextField(null=True),
        ),
    ]
